export const initialTestimonials = [
  { name: "Dieudonné Atangana", role: "P2P Merchant", content: "The best P2P experience in Cameroon. I sell my USDT and get XAF in my MoMo account in record time. Zero stress.", rating: 5 },
  { name: "Pascaline Foning", role: "Crypto Trader", content: "I've used many P2P groups, but Zaptopay is on another level. Secure, fast, and the rates are always the most competitive for selling BTC.", rating: 5 },
  { name: "Ibrahim Moussa", role: "USDT Specialist", content: "Reliable P2P gateway for Douala traders. The escrow system and verified agents make every large USDT-to-XAF trade feel safe.", rating: 4 },
  { name: "Marie-Claire Ngo", role: "Business Arbitrage", content: "Seamless P2P off-ramping. I handle high-volume crypto sales here because the liquidity and speed are unmatched in the CEMAC zone.", rating: 5 },
  { name: "Abodo Ndjana", role: "Node Operator", content: "The fastest way to liquidate mining profits. I sell my crypto directly to their P2P desk and receive Orange Money instantly.", rating: 5 },
  { name: "Kamga Fotso", role: "Finance Consultant", content: "Institutional grade P2P service. No more dealing with unreliable telegram dealers. Zaptopay is the professional way to buy and sell crypto.", rating: 5 },
  { name: "Ekane Sali", role: "Tech Entrepreneur", content: "Great UI but even better execution. Their p2p workflow is optimized for mobile traders who need XAF on the go. Simply the best.", rating: 5 },
  { name: "Njoh Ewané", role: "International Freelancer", content: "I get paid in USDT and sell it on Zaptopay's P2P platform. The funds hit my account before I can even send the confirmation.", rating: 5 },
  { name: "Sime Kouam", role: "Import/Export", content: "Perfect for business liquidity. I sell crypto to pay my local suppliers in XAF. Fast, verified, and highly professional P2P.", rating: 4 },
  { name: "Ngassa Tabi", role: "Verified P2P Agent", content: "As an agent, I can confirm the system is robust. Best platform for secure p2p mediation and high-speed settlement.", rating: 5 },
  { name: "Bakari Bello", role: "Cattle Trader", content: "Swift and easy. Even a beginner can use this. Much respect for the speed.", rating: 5 },
  { name: "Fabiola Mbarga", role: "Art Curator", content: "Smooth experience every time. The rate calculator is very helpful for planning my trades.", rating: 4 },
  { name: "Christian Nkolo", role: "Software Engineer", content: "API-like speed for manual trades. This platform is ahead of its time in Cameroon.", rating: 5 },
  { name: "Chantal Abena", role: "Retailer", content: "I use it for all my crypto to XAF needs. It's simply the best in Douala.", rating: 5 },
  { name: "Oumarou Diallo", role: "Logistics", content: "Transactions are truly instant. I was shocked the first time I used it. Verified!", rating: 5 },
  { name: "Solange Mbia", role: "Teacher", content: "Easy to use even on mobile. Great rates for my small savings in Bitcoin.", rating: 4 },
  { name: "Rodrigue Eboué", role: "Event Manager", content: "Zaptopay has replaced my local p2p groups. Much safer and definitely faster.", rating: 5 },
  { name: "Nadège Tchakounté", role: "Student", content: "I love the vibe of the site. Trading here is fun and the payouts are instant.", rating: 5 },
  { name: "Jean-Paul Epale", role: "Tourism", content: "Reliable service for my crypto payouts. Best in Kribi and beyond!", rating: 5 },
  { name: "Aminatou Sambo", role: "Pharmacist", content: "Clean, fast, and secure. Everything a professional needs for crypto transactions.", rating: 5 },
  // ... adding more to reach 100+
  { name: "Blaise Ngu", role: "Verified User", content: "Awesome rates, super fast service. 5 stars!", rating: 5 },
  { name: "Sidonie Batake", role: "Crypto Pioneer", content: "The best thing to happen to the Cameroonian crypto space. Truly seamless.", rating: 5 },
  { name: "Prosper Mvondo", role: "Trader", content: "I never worry about my funds. The verification process is thorough.", rating: 5 },
  { name: "Bertrand Njoya", role: "Consultant", content: "Professional and lightning quick. The agents are very respectful too.", rating: 4 },
  { name: "Alice Nkodo", role: "Entrepreneur", content: "Love the new look! And the speed is still as great as day one.", rating: 5 },
  { name: "Cyrille Etoga", role: "Logistics Manager", content: "Reliable and fast. The best way to get XAF from my crypto holdings.", rating: 5 },
  { name: "Doris Ngando", role: "Chef", content: "Even my grandma can understand this! Simple and straightforward.", rating: 5 },
  { name: "Emery Bassong", role: "Music Producer", content: "Keep up the good work. Zaptopay is a diamond in the rough.", rating: 4 },
  { name: "Félix Mebenga", role: "Farmer", content: "Good service, fast money. No complaints.", rating: 5 },
  { name: "Giselle Ebogo", role: "Fashion Designer", content: "Premium feel, premium service. My favorite crypto app.", rating: 5 },
  { name: "Hubert Njome", role: "Engineer", content: "Efficient systems. The automation is impressive.", rating: 5 },
  { name: "Irène Belinga", role: "Nurse", content: "Very helpful for emergency cash needs from my wallet.", rating: 4 },
  { name: "Justin Tabot", role: "Project Manager", content: "Solid platform. High security and fast processing.", rating: 5 },
  { name: "Kenfack Boris", role: "Mobile Dev", content: "Love the UI/UX. The best design in cameroonian fintech.", rating: 5 },
  { name: "Léonie Massango", role: "Waitress", content: "Honest rates and fast Pay. Thank you Zaptopay.", rating: 5 },
  { name: "Marcelle Onana", role: "Accountant", content: "Precise and reliable. Great for tracking my trade history too.", rating: 5 },
  { name: "Noël Dikongué", role: "Journalist", content: "Informative and fast. A trusted source for exchange.", rating: 4 },
  { name: "Odile Ngono", role: "Social Worker", content: "Helps me manage my crypto savings easily.", rating: 5 },
  { name: "Paulin Biyong", role: "Architect", content: "Structured and secure trade. I really appreciate the transparency.", rating: 5 },
  { name: "Quintance Njoh", role: "Sales Rep", content: "Fastest MoMo cashout I've ever experienced.", rating: 5 },
  { name: "Raissa Efala", role: "Advocate", content: "Legally sound and secure feeling platform. Well done.", rating: 5 },
  { name: "Serge Mvondo", role: "Gym Trainer", content: "Quick cash after my trades. Perfect timing always.", rating: 5 },
  { name: "Thérèse Atangana", role: "Grocer", content: "Small trades or big trades, they handle all with speed.", rating: 4 },
  { name: "Ursule Ndom", role: "Tailor", content: "Very reliable. I always get my money on time.", rating: 5 },
  { name: "Valery Kome", role: "Driver", content: "Good rates for USDT. Better than my local dealer.", rating: 5 },
  { name: "Willy Ngassa", role: "Artist", content: "Creative design and smooth function. Total 5 stars.", rating: 5 },
  { name: "Xaverie Mbia", role: "Student", content: "Easy to use on campus. Love the speed.", rating: 4 },
  { name: "Yannick Noah", role: "Sports Coach", content: "Champion service. Fastest XAF transfers.", rating: 5 },
  { name: "Zra Moussa", role: "Merchant", content: "Trusted by the north and south. Zaptopay is everywhere.", rating: 5 },
  // ... another block to reach 100
  { name: "Armel Djouka", role: "Entrepreneur", content: "Unbeatable experience.", rating: 5 },
  { name: "Béatrice Fomekong", role: "Lawyer", content: "Safe and fast. No issues.", rating: 5 },
  { name: "Cédric Mballa", role: "Tech Lead", content: "The future of crypto in Cameroon is Zaptopay.", rating: 5 },
  { name: "Desiré Ngwa", role: "Trader", content: "Fastest MoMo out there.", rating: 5 },
  { name: "Eloi Mendomo", role: "Professor", content: "Educational and efficient.", rating: 4 },
  { name: "Françoise Mbia", role: "Business Lady", content: "My daily app for crypto.", rating: 5 },
  { name: "Gérard Ebogo", role: "Retired", content: "Simple even for me. Very nice.", rating: 5 },
  { name: "Hortense Atangana", role: "Doctor", content: "Highly reliable for quick funds.", rating: 5 },
  { name: "Ignace Noah", role: "Marketing", content: "Best rates, no contest.", rating: 4 },
  { name: "Juliette Nkolo", role: "Secretary", content: "Quick and easy, just how I like it.", rating: 5 },
  { name: "Kevin Ngante", role: "Gamer", content: "Smooth like a 120Hz display.", rating: 5 },
  { name: "Lucie Mbida", role: "Pharmacist", content: "Very secure transactions.", rating: 5 },
  { name: "Mathieu Tagne", role: "Builder", content: "Solid as a rock. Trade with peace of mind.", rating: 5 },
  { name: "Nicole Abena", role: "Stylist", content: "Beautiful app, beautiful speed.", rating: 5 },
  { name: "Ondoua Pierre", role: "Driver", content: "Good service for us on the road.", rating: 4 },
  { name: "Prisca Ngono", role: "Vendor", content: "Takes less than 2 minutes usually. Amazing.", rating: 5 },
  { name: "Quentin Fosso", role: "Developer", content: "Clean API and clean UI. Impressive.", rating: 5 },
  { name: "Ramses Atangana", role: "Musician", content: "Rocking the crypto world in CMR.", rating: 5 },
  { name: "Sylvain Mvondo", role: "Security", content: "Top notch safety protocols.", rating: 5 },
  { name: "Tatiana Nkodo", role: "HR Manager", content: "Professional and timely.", rating: 4 },
  { name: "Urbain Njoh", role: "Pilot", content: "Fast as a jet. Highly recommended.", rating: 5 },
  { name: "Viviane Efala", role: "Biologist", content: "Precise exchange rates.", rating: 5 },
  { name: "Walfred Kome", role: "Researcher", content: "Verified data and fast trades.", rating: 5 },
  { name: "Xavier Ngu", role: "Actor", content: "The best performance in crypto apps.", rating: 5 },
  { name: "Yvette Mballa", role: "Dancer", content: "Graceful and quick service.", rating: 4 },
  { name: "Zacharie Noah", role: "Farmer", content: "Harvesting crypto made easy.", rating: 5 },
  { name: "Abel Ngome", role: "Butcher", content: "Good price, good speed.", rating: 5 },
  { name: "Boris Kenfack", role: "Tutor", content: "Learning to trade was easy with this.", rating: 5 },
  { name: "Carine Atangana", role: "Librarian", content: "Quietly efficient. Love it.", rating: 5 },
  { name: "Dimitri Ngwa", role: "Photographer", content: "Picture perfect trades.", rating: 5 },
  { name: "Esther Mbia", role: "Nurse", content: "Careful and quick processing.", rating: 4 },
  { name: "Florent Ebogo", role: "Gardener", content: "Growing my savings with Zaptopay.", rating: 5 },
  { name: "Guy Nkolo", role: "Chef", content: "The secret ingredient for fast cash.", rating: 5 },
  { name: "Huguette Atangana", role: "Writer", content: "A story of success in every trade.", rating: 5 },
  { name: "Inès Noah", role: "Designer", content: "Sleek and functional.", rating: 5 },
  { name: "Joël Njoh", role: "Electrician", content: "Powerful service. High voltage speed.", rating: 4 },
  { name: "Karine Efala", role: "Model", content: "Looking good, working better.", rating: 5 },
  { name: "Lionel Mvondo", role: "Coach", content: "Leading the pack in Cameroon.", rating: 5 },
  { name: "Mirielle Ngono", role: "Waitress", content: "Always gets my tips right.", rating: 5 },
  { name: "Norbert Atangana", role: "Guard", content: "Always on watch for best rates.", rating: 5 },
  { name: "Olivia Mbida", role: "Manager", content: "Perfect for my business needs.", rating: 4 },
  { name: "Patrick Fosso", role: "Techie", content: "Best crypto-to-xaf gateway.", rating: 5 },
  { name: "Queen Ngome", role: "Royal Business", content: "Service fit for a queen.", rating: 5 },
  { name: "Raoul Atangana", role: "Soldier", content: "Disciplined and fast.", rating: 5 },
  { name: "Sonia Mballa", role: "Stylist", content: "Always in fashion with crypto.", rating: 5 },
  { name: "Titus Noah", role: "Student", content: "Study hard, trade fast.", rating: 4 },
  { name: "Ulrich Ngwa", role: "Gamer", content: "No lag in transactions.", rating: 5 },
  { name: "Vanessa Ebogo", role: "Blogger", content: "The hype is real. Zaptopay rocks.", rating: 5 },
];
